# Generated by Django 5.1.1 on 2024-11-01 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'calc_choose',
                'managed': True,
            },
        ),
    ]
