# Generated by Django 5.1.1 on 2024-11-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='calcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=255)),
                ('desc_extended', models.TextField()),
                ('image', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'calcs',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='user_calcs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'user_calcs',
            },
        ),
        migrations.DeleteModel(
            name='cards',
        ),
    ]
