# Generated by Django 5.1.1 on 2024-11-05 10:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_calcs_user_calcs_delete_cards'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='calculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField(verbose_name='Сумма')),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('status', models.IntegerField(choices=[(1, 'draft'), (0, 'deleted'), (2, 'formed'), (3, 'completed'), (4, 'rejected')], default=1, verbose_name='Статус')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'calculation',
                'verbose_name_plural': 'calculations',
                'db_table': 'calculation',
            },
        ),
        migrations.CreateModel(
            name='calculation_content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.calculation')),
            ],
            options={
                'verbose_name': 'calculation_content',
                'verbose_name_plural': 'calculation_content',
                'db_table': 'calculation_content',
            },
        ),
        migrations.CreateModel(
            name='mortgage_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('desc_extended', models.TextField(verbose_name='Расширенное описание')),
                ('image', models.URLField(blank=True, null=True, verbose_name='Изображение')),
                ('status', models.BooleanField(choices=[(True, 'active'), (False, 'deleted')], default='active', verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'mortgage',
                'verbose_name_plural': 'mortgages',
                'db_table': 'mortgage',
            },
        ),
        migrations.DeleteModel(
            name='calcs',
        ),
        migrations.DeleteModel(
            name='user_calcs',
        ),
        migrations.AddField(
            model_name='calculation_content',
            name='mortgage_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.mortgage_list'),
        ),
        migrations.AlterUniqueTogether(
            name='calculation_content',
            unique_together={('calculation', 'mortgage_type')},
        ),
    ]
