# Generated by Django 5.1.1 on 2024-11-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_calculation_calculation_content_mortgage_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mortgage_list',
            name='desc_extended',
            field=models.TextField(blank=True, verbose_name='Расширенное описание'),
        ),
    ]
