# Generated by Django 5.1.1 on 2024-11-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_mortgage_list_desc_extended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculation',
            name='value',
            field=models.IntegerField(default=1000000, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='calculation_content',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
    ]
